app/docusign/views.py
from datetime import datetime, timedelta

from flask import redirect, request, url_for, flash, render_template, Blueprint, session, current_app as app

import json
from .ds_client import DSClient
from .utils import ds_logout_internal, get_manifest, is_cfr
from ..consts import base_uri_suffix
from ..ds_config import DS_CONFIG
from ..api_type import EXAMPLES_API_TYPE

ds = Blueprint("ds", __name__, url_prefix="/ds")
manifest_url = DS_CONFIG["example_manifest_url"]

@ds.route("/login", methods=["GET", "POST"])
def ds_login():
    if session.get('manifest'):
        session.pop('manifest')

    if not session.get("auth_type"):
        session["auth_type"] = request.form.get("auth_type")

    session["manifest"] = get_manifest(manifest_url)

    app.config["isLoggedIn"] = True
    app.config["quickstart"] = DS_CONFIG["quickstart"]
    return DSClient.login(session["auth_type"], session.get("api"))


@ds.route("/logout")
def ds_logout():
    ds_logout_internal()
    flash("You have logged out from DocuSign.")
    app.config["isLoggedIn"] = False
    app.config["quickstart"] = False

    return redirect(url_for("core.index"))

@ds.route("/choose_api")
def choose_api():
    session["manifest"] = get_manifest(manifest_url)
    return render_template("choose_api.html", title="Choose API", manifest=session["manifest"])

@ds.route("/api_selected", methods=["GET", "POST"])
def api_selected():
    chosen_api = request.form.get("chosen_api")

    new_api_type = EXAMPLES_API_TYPE

    # Set all values to False
    for api_type in new_api_type:
        if new_api_type[api_type] == True:
            new_api_type[api_type] = False

    # Update the new chosen API type to True
    if chosen_api == "ESignature":
        new_api_type["ESignature"] = True
    elif chosen_api == "Rooms":
        new_api_type["Rooms"] = True
    elif chosen_api == "Admin":
        new_api_type["Admin"] = True
    elif chosen_api == "Monitor":
        new_api_type["Monitor"] = True
    elif chosen_api == "Click":
        new_api_type["Click"] = True 

    # Overwrite api_type.py file
    with open("app/api_type.py", "w") as api_type_file:
        api_type_file.write("EXAMPLES_API_TYPE =" + str(new_api_type))

    ds_logout_internal()
    flash("You have logged out from DocuSign.")
    app.config["isLoggedIn"] = False
    app.config["quickstart"] = False

    session["manifest"] = get_manifest(manifest_url)
    return render_template("must_authenticate.html", title="Must authenticate", chosen_api=chosen_api, manifest=session["manifest"])


@ds.route("/callback")
def ds_callback():
    """
    Save the token information in session.
    Call api to get user's information if it doesn't present
    """

    # Save the redirect eg if present
    redirect_url = session.pop("eg", None)
    resp = DSClient.get_token(session["auth_type"])

    # app.logger.info("Authenticated with DocuSign.")
    session["ds_access_token"] = resp["access_token"]
    session["ds_refresh_token"] = resp["refresh_token"]
    session["ds_expiration"] = datetime.utcnow() + timedelta(seconds=int(resp["expires_in"]))

    if not session.get("ds_account_id"):
        flash("You have authenticated with DocuSign.")
        # Request to API to get the user information
        response = DSClient.get_user(session["ds_access_token"])
        session["ds_user_name"] = response["name"]
        session["ds_user_email"] = response["email"]
        accounts = response["accounts"]
        # Find the account...
        target_account_id = DS_CONFIG["target_account_id"]
        if target_account_id:
            account = next((a for a in accounts if a["account_id"] == target_account_id), None)
            if not account:
                # The user does not have the targeted account. They should not log in!
                raise Exception("No access to target account")
        else:  # get the default account
            account = next((a for a in accounts if a["is_default"]), None)
            if not account:
                # Every user should always have a default account
                raise Exception("No default account")

        # Save the account information
        session["ds_account_id"] = account["account_id"]
        session["ds_account_name"] = account["account_name"]
        session["ds_base_path"] = account["base_uri"] + base_uri_suffix

    if EXAMPLES_API_TYPE["ESignature"] == "true":
        session["is_cfr"] = is_cfr(session["ds_access_token"], session["ds_account_id"], session["ds_base_path"])

    if not redirect_url:
        redirect_url = url_for("core.index")
    return redirect(redirect_url)


@ds.route("/must_authenticate")
def ds_must_authenticate():
    if DS_CONFIG["quickstart"] == "true" and EXAMPLES_API_TYPE["ESignature"]:
        session["auth_type"] = "code_grant"
        return redirect(url_for("ds.ds_login"))

    elif EXAMPLES_API_TYPE["Monitor"]:
        session["auth_type"] = "jwt"
        return redirect(url_for("ds.ds_login"))

    else:
        session["manifest"] = get_manifest(manifest_url)
        return render_template("must_authenticate.html", title="Must authenticate", manifest=session["manifest"])


@ds.route("/ds_return")
def ds_return():
    event = request.args.get("event")
    state = request.args.get("state")
    envelope_id = request.args.get("envelopeId")
    DS_CONFIG["quickstart"] = "false"

    session["manifest"] = get_manifest(manifest_url)
    return render_template(
        "ds_return.html",
        title="Return from DocuSign",
        event=event,
        envelope_id=envelope_id,
        state=state,
        manifest=session["manifest"]
    )

app/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{{ url_for('static', filename='assets/favicon.ico') }}">
    <title>{{ title }}</title>
    <!-- Bootstrap core CSS -->
    <script src="https://kit.fontawesome.com/a2fb399780.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <!-- Custom styles for this template -->
    <link href="{{ url_for('static', filename='assets/css.css') }}" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <a class="navbar-brand" href="/">DocuSign Examples</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/">{{ session["manifest"]["SupportingTexts"]["HomeButton"] }} <span class="sr-only">(current)</span></a>
          </li>

          {% if session['ds_user_name'] %}
            <li>
              <a class="nav-link" href="{{ url_for('ds.ds_logout') }}" id="logout"
                 data-busy="href">{{ session["manifest"]["SupportingTexts"]["LogoutButton"] }} <span class="sr-only">(current)</span></a>
            </li>
          {% else %}
            <li>
              <a class="nav-link" href="{{ url_for('ds.ds_must_authenticate') }}" id="login"
                 data-busy="href">{{ session["manifest"]["SupportingTexts"]["LoginButton"] }} <span class="sr-only">(current)</span></a>
            </li>
          {% endif %}
        </ul>

        {% if session['ds_user_name'] %}
          <span class="navbar-text">
            Welcome {{ session['ds_user_name'] }}
          </span>
        {% endif %}

      </div>
    </nav>

    <!-- <div class="container">
      {% if session['ds_account_name'] %}
          <p>DocuSign Account: {{ session['ds_account_name'] }}.</p>
      {% endif %} -->

      <div class="col-md-12 feedback" id="feedback">
          <h3>Working...&nbsp;&nbsp;&nbsp;<span></span></h3>
      </div>

      <section id="busy" class="feedback"><div class="spinner">
        <div class="rect1"></div>
        <div class="rect2"></div>
        <div class="rect3"></div>
        <div class="rect4"></div>
        <div class="rect5"></div>
        </div>
      </section>

      <p id="download-continue" class="feedback"><a href="/">c</a></p>

      {% if 'ds_user_name' in session %}
        <div class="container">
           <section id="content" style="padding-top:30px;">
      {%  else  %}
        <div class="container-full-bg">
            <section id="content" style="margin-top:-60px!important; padding-top:30px!important;">
      {% endif %}
                {% block content %}{% endblock %}
      </section>
    </div>
    
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  
    <script src="https://cdn.jsdelivr.net/npm/lodash@4.17.5/core.min.js"></script>

    <script src="{{ url_for('static', filename='assets/notify.min.js') }}"></script> <!-- see https://notifyjs.jpillora.com/ -->
    <script src="{{ url_for('static', filename='assets/eg_03.js') }}"></script>
    
    <!-- Data from the server -->
    {% set json_messages = get_flashed_messages() | tojson %}
    <div id="server_data"
         data-server-data='{"flash": {"info": {{ json_messages | safe }} } }'
         class="hidden">
    </div>
  </body>
</html>

app/templates/cfr_error.html
<!-- extend base layout -->
{% extends "base.html" %}
{% set title = "Error" %}
{% block content %}

<h2>Problem: an error occurred</h2>
<p>Error information:</p>

<p>{{ session['manifest']['SupportingTexts']['CFRError'] }}</p>

<p><a href="/">Continue</a></p>
  
{% endblock %}

app/templates/cfr_home.html
<!-- extend base layout -->
{% extends "base.html" %}

{% block content %}

    {% if not 'ds_user_name' in session %}
  <!-- IF not signed in -->
  <div>
    <div class="jumbotron jumbotron-fluid"> <table>
      <tbody>
      <tr>
      <td>
        <h1 class="display-4">Python Launcher</h1>
      <p class="Xlead">{{ session['manifest']['SupportingTexts']['HomePageText'] }}</p>
      </td>
      <td>
          <img src="/static/assets/banner-code.png" />
      </td>
    </tr>
    </tbody>
    </table>
  </div>
    {% endif %}

    <!--  Future: add a table of contents or navigation pane
          Eg, see https://stackoverflow.com/questions/21868610/make-column-fixed-position-in-bootstrap
    -->

    <div class="container" style="margin-top: 40px" id="index-page">
        <div class="form-group has-search">
            <span class="fa fa-search form-control-feedback"></span>
            <input type="text" class="form-control" id="code_example_search" placeholder="Search for code example">
        </div>

        <div id="filtered_code_examples" class="container" style="margin-top: 10px; padding-left: 0px;">

            {% if show_doc %}
                <p><a target='_blank' href='{{ documentation | safe }}'>Documentation</a> on using JWT or Authorization Code Grant from a Python Flask application.</p>
            {% endif %}

            {% for api in manifest['APIs'] -%}
                {% for group in api['Groups'] -%}
                    <h2>{{ group["Name"] }}</h2>

                    {% for example in group["Examples"] -%}
                        {% if not example["SkipForLanguages"] or "python" not in example["SkipForLanguages"] %}
                            {% if example.CFREnabled == "AllAccounts" or example.CFREnabled == "CFROnly" %}
                                {% set api_prefix = "a" if api["Name"] == "Admin" else "c" if api["Name"] == "Click" else "r" if api["Name"] == "Rooms" else "m" if api["Name"] == "Monitor" else "w" if api["Name"] == "WebForms" else "" %}
                                <h4
                                    id="{{ api_prefix + 'example' + '0' * (3 - example['ExampleNumber'] | string() | length ) + example['ExampleNumber'] | string() }}"
                                >
                                    <a
                                        href="{{ api_prefix + 'eg' + '0' * (3 - example['ExampleNumber'] | string() | length ) + example['ExampleNumber'] | string() }}">{{ example["ExampleName"] }}
                                    </a>
                                </h4>

                                <p>{{ example["ExampleDescription"] | safe }}</p>

                                {% if example["LinksToAPIMethod"] | length > 1 %}
                                    {{ session["manifest"]["SupportingTexts"]["APIMethodUsedPlural"] | safe }}
                                {% else %}
                                    {{ session["manifest"]["SupportingTexts"]["APIMethodUsed"] | safe }}
                                {% endif %}

                                {% for link in example["LinksToAPIMethod"] -%}
                                  <a target='_blank' href="{{ link['Path'] }}">{{ link['PathName'] }}</a>
                             {% endfor %}
                                <br></br>
                            {% endif %}
                        {% endif %}
                    {% endfor %}
                {% endfor %}
            {% endfor %}
        </div>

        <div id="api_json_data" class="hidden">{{ manifest | to_json }}</div>
        <div id="cfr11_data" class="hidden">{{ crfEnabled }}</div>
    </div>

    <!-- anchor-js is only for the index page -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/anchor-js/4.1.1/anchor.min.js"></script>
    <script>anchors.options.placement = 'left'; anchors.add('h4')</script>
    <script src="https://cdn.jsdelivr.net/npm/fuse.js@6.6.2"></script>
    <script src="/static/assets/search.js"></script>

    {% endblock %}

app/templates/continue_button.html
<button type="submit" class="btn btn-docu">{{ session['manifest']['SupportingTexts']['ContinueButton'] }}</button>

app/templates/ds_return.html
<!-- extend base layout --> {% extends "base.html" %}  {% block content %}

<h2>Returned data from DocuSign!</h2>
<p>Data:</p>

{% if event %}
  <p><b>event: {{ event }}.</b> This event parameter is supplied by DocuSign.
    Since it could have been spoofed, don't make business decisions based on
    its value. Instead, query DocuSign as appropriate.</p>
{% endif %}

{% if envelope_id %}
  <p><b>envelopeId: {{ envelope_id }}.</b> The envelopeId parameter is supplied by DocuSign.
    Since it could have been spoofed, don't make business decisions based on
    its value. Instead, query DocuSign as appropriate.</p>
{% endif %}

{% if state %}
  <p><b>state: {{ state }}</b> This example state was sent to DocuSign and has now been received back.
     It is usually better to store state in your web framework's session.</p>
{% endif %}

<p><a href="/">Continue</a></p>
  
{% endblock %}

app/templates/eg001_embedded_signing.html
<!-- extend base layout --> {% extends "base.html" %}  {% block content %}

{% include 'example_info.html' %}

{%  set signer_form_index = 0 %}
{%  set signer_email_index = 0 %}
{%  set signer_name_index = 1 %}

<form class="eg" action="" method="post" data-busy="form">
    {% if 'FormName' in example['Forms'][signer_form_index] %}
        <p>{{ example['Forms'][signer_form_index]['FormName'] | safe }}</p>
    {% endif %}

    <div class="form-group">
      <label for="signer_email">{{ example['Forms'][signer_form_index]['Inputs'][signer_email_index]['InputName'] }}</label>
      <input type="email" class="form-control" id="signer_email" name="signer_email"
             aria-describedby="emailHelp" placeholder="{{ example['Forms'][signer_form_index]['Inputs'][signer_email_index]['InputPlaceholder'] }}" required
             value="{{ signer_email }}">
      <small id="emailHelp" class="form-text text-muted">{{ session['manifest']['SupportingTexts']['HelpingTexts']['EmailWontBeShared'] | safe}}</small>
    </div>
    <div class="form-group">
      <label for="signer_name">{{ example['Forms'][signer_form_index]['Inputs'][signer_name_index]['InputName'] }}</label>
      <input type="text" class="form-control" id="signer_name" placeholder="{{ example['Forms'][signer_form_index]['Inputs'][signer_name_index]['InputPlaceholder'] }}" name="signer_name"
             value="{{ signer_name }}" required>
    </div>
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
    {% include 'submit_button.html' %}
  </form>
  
{% endblock %}

app/templates/error.html
<!-- extend base layout -->
{% extends "base.html" %}
{% set title = "Error" %}
{% block content %}

<h2>Problem: an error occurred</h2>
<p>Error information:</p>

{% if error_code %}
  <p>{{ error_code }}: {{ error_message | safe }}</p>
{% else %}
  <p><pre>{{ err }}</pre></p>
{% endif %}

<p><a href="/">Continue</a></p>
  
{% endblock %}

app/templates/example_done.html
<!-- extend base layout --> {% extends "base.html" %}  {% block content %}

{% if 'ds_user_name' in session %}
  <div>
{% else %}
  <div style="margin:30px 90px 0 90px; padding:15px 15px 0 15px;">
{% endif %}
    <h2>{{ title }}</h2>
    <p>{{ message | safe }}</p>

    {% if json %}
      <!-- Data from the server -->
      <div id="server_json_data" data-server-json-data='{"json": {{ json | safe }} }' class="hidden"></div>
      <p><pre class="json-display"><code id="json-display"></code></pre></p>
    {%  endif %}

    {% if changed_settings %}
        <ul>
            {% for k, v in changed_settings.items() %}
                <li><b>{{ k }}:</b> {{ v }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    {% if redirect_url %}
        <p><a href="{{ redirect_url }}">Continue</a></p>
    {% else %}
        <p><a href="/">Continue</a></p>
    {% endif %}
</div>

{% endblock %}

app/templates/example_info.html
<h4>{{ title }}</h4>
<p>{{ example["ExampleDescription"] | safe }}</p>

{% if show_doc %}
    <p><a target='_blank' href='{{ documentation | safe }}'>Documentation</a> about this example.</p>
{% endif %}

{% if "Note" in example %}
    <p>{{ example["Note"] | safe }}</p>
{% endif %}

{% if example["LinksToAPIMethod"] | length > 0 %}
    {% if example["LinksToAPIMethod"] | length > 1 %}
        {{ session["manifest"]["SupportingTexts"]["APIMethodUsedPlural"] | safe }}
    {% else %}
        {{ session["manifest"]["SupportingTexts"]["APIMethodUsed"] | safe }}
    {% endif %}

    {% for link in example["LinksToAPIMethod"] -%}
        <a target='_blank' href="{{ link['Path'] }}">{{ link['PathName'] }}</a>
    {% endfor %}
{% endif %}

<p>
    View source file <a target="_blank" href="{{ source_url | safe }}">{{ source_file }}</a> on GitHub.
</p>

app/templates/example_rooms_6_done.html
<!-- extend base layout --> {% extends "base.html" %}  {% block content %}

<h2>{{ title }}</h2>
<p>{{ message | safe }}</p>

<p> Results from the ExternalFormFillSessions::CreateExternalFormFillSession: </p>
<p><code>{{json}}</code></p>

<p style="color:white;">
#ds-snippet-start:Rooms6Step5
<iframe width="1000" height="800" src = "{{url}}" >

</iframe>
#ds-snippet-end:Rooms6Step5
</p>

{% if changed_settings %}
    <ul>
        {% for k, v in changed_settings.items() %}
            <li><b>{{ k }}:</b> {{ v }}</li>
        {% endfor %}
    </ul>
{% endif %}

<p><a href="/">Continue</a></p>
  
{% endblock %}

app/templates/home.html
<!-- extend base layout -->
{% extends "base.html" %}

{% block content %}

    {% if not 'ds_user_name' in session %}
  <!-- IF not signed in -->
  <div>
    <div class="jumbotron jumbotron-fluid"> <table>
      <tbody>
      <tr>
      <td>
        <h1 class="display-4">Python Launcher</h1>
      <p class="Xlead">{{ session['manifest']['SupportingTexts']['HomePageText'] }}</p>
      </td>
      <td>
          <img src="/static/assets/banner-code.png" />
      </td>
    </tr>
    </tbody>
    </table>
  </div>
    {% endif %}

    <!--  Future: add a table of contents or navigation pane
          Eg, see https://stackoverflow.com/questions/21868610/make-column-fixed-position-in-bootstrap
    -->

    <div class="container" style="margin-top: 40px" id="index-page">
        <div class="form-group has-search">
            <span class="fa fa-search form-control-feedback"></span>
            <input type="text" class="form-control" id="code_example_search" placeholder="Search for code example">
        </div>

        <div id="filtered_code_examples" class="container" style="margin-top: 10px; padding-left: 0px;">

            {% if show_doc %}
                <p><a target='_blank' href='{{ documentation | safe }}'>Documentation</a> on using JWT or Authorization Code Grant from a Python Flask application.</p>
            {% endif %}

            {% for api in manifest['APIs'] -%}
                {% for group in api['Groups'] -%}
                    <h2>{{ group["Name"] }}</h2>

                    {% for example in group["Examples"] -%}
                        {% if not example["SkipForLanguages"] or "python" not in example["SkipForLanguages"] %}
                            {% if example.CFREnabled != "CFROnly" %}
                                {% set api_prefix = "a" if api["Name"] == "Admin" else "c" if api["Name"] == "Click" else "r" if api["Name"] == "Rooms" else "m" if api["Name"] == "Monitor" else "cn" if api["Name"] == "Connect" else "ms" if api["Name"] == "Maestro" else "w" if api["Name"] == "WebForms" else "" %}
                                <h4
                                    id="{{ api_prefix + 'example' + '0' * (3 - example['ExampleNumber'] | string() | length ) + example['ExampleNumber'] | string() }}"
                                >
                                    <a
                                        href="{{ api_prefix + 'eg' + '0' * (3 - example['ExampleNumber'] | string() | length ) + example['ExampleNumber'] | string() }}">{{ example["ExampleName"] }}
                                    </a>
                                </h4>

                                <p>{{ example["ExampleDescription"] | safe }}</p>

                                {% if example["LinksToAPIMethod"] | length > 0 %}
                                    {% if example["LinksToAPIMethod"] | length > 1 %}
                                        {{ session["manifest"]["SupportingTexts"]["APIMethodUsedPlural"] | safe }}
                                    {% else %}
                                        {{ session["manifest"]["SupportingTexts"]["APIMethodUsed"] | safe }}
                                    {% endif %}
                                    
                                    {% for link in example["LinksToAPIMethod"] -%}
                                      <a target='_blank' href="{{ link['Path'] }}">{{ link['PathName'] }}</a>
                                    {% endfor %}
                                    <br></br>
                                {% endif %}
                            {% endif %}
                        {% endif %}
                    {% endfor %}
                {% endfor %}
            {% endfor %}
        </div>

        <div id="api_json_data" class="hidden">{{ manifest | to_json }}</div>
        <div id="cfr11_data" class="hidden">{{ crfEnabled }}</div>
    </div>

    <!-- anchor-js is only for the index page -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/anchor-js/4.1.1/anchor.min.js"></script>
    <script>anchors.options.placement = 'left'; anchors.add('h4')</script>
    <script src="https://cdn.jsdelivr.net/npm/fuse.js@6.6.2"></script>
    <script src="/static/assets/search.js"></script>

    {% endblock %}

app/templates/must_authenticate.html
<!-- extend base layout -->
{% extends "base.html" %}

{% block content %}
{% if chosen_api == "Monitor" %}
<div style="margin:1% 5%;">
    {{ session["manifest"]["SupportingTexts"]["LoginPage"]["LoginHeader"] | safe }}

  <form method="post" data-busy="form" action={{ url_for("ds.ds_login") }}>
      <div class="form-group col-md-5">
          <select class="form-control" id="auth_type" name="auth_type">
              <option value="jwt">JSON Web Token</option>
          </select>
          <p class="lead" style="padding-top: .5rem;">
              <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
              <button type="submit" class="btn btn-docu">{{ session["manifest"]["SupportingTexts"]["LoginPage"]["LoginButton"] }}</button>
          </p>
      </div>
  </form>
    <hr class="my-4">
  </div>

{% else %}

    <div style="margin:1% 5%;">
    {{ session["manifest"]["SupportingTexts"]["LoginPage"]["LoginHeader"] | safe }}

    <form method="post" data-busy="form" action={{ url_for("ds.ds_login") }}>
        <div class="form-group col-md-5">
            <select class="form-control" id="auth_type" name="auth_type">
                <option value="code_grant">Authorization Code Grant</option>
                <option value="jwt">JSON Web Token</option>
            </select>
            <p class="lead" style="padding-top: .5rem;">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                <button type="submit" class="btn btn-docu">{{ session["manifest"]["SupportingTexts"]["LoginPage"]["LoginButton"] }}</button>
            </p>
        </div>
    </form>
      <hr class="my-4">
    </div>
{% endif %}
{% endblock %}

app/templates/submit_button.html
<button type="submit" class="btn btn-docu">{{ session['manifest']['SupportingTexts']['SubmitButton'] }}</button>